"""Plot training curves, predictions, and active-learning convergence."""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import os
from pathlib import Path
import h5py
import pandas as pd

def plot_train_val_convergence(csv_path: str, save_path: str, log_scale: bool = True):
    """
    Plot training and validation loss curves from the train_metrics_{fold}.csv
    file generated by the trainer during training.
    """
    if not os.path.exists(csv_path):
        print(f"[Warning] {csv_path} not found. Skipping convergence plot.")
        return

    df = pd.read_csv(csv_path)

    plt.figure(figsize=(10, 6), dpi=150)
    plt.plot(df["epoch"], df["train_loss"], label="Train Loss", color="#1f77b4", linewidth=2.0)
    plt.plot(df["epoch"], df["val_loss"], label="Val Loss", color="#ff7f0e", linewidth=2.0)

    if log_scale:
        plt.yscale("log")
        title = "Training & Validation Loss (log scale)"
    else:
        title = "Training & Validation Loss"

    plt.title(title, fontsize=14)
    plt.xlabel("Epoch", fontsize=12)
    plt.ylabel("Loss", fontsize=12)
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend(fontsize=11, loc="upper right")
    plt.tight_layout()

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {save_path}")

def plot_predictions_vs_true(
    results,
    config,
    save_dir,
    y_normalizer,
    x_normalizer=None,
    n_samples=20,
    percentile_range=(5, 95),
    xlim=None,
    X=None,
    sample_indices=None,          # NEW: if provided, plot exactly these indices (bypass auto-selection)
):
    """N rows (evenly spread from best 5% to worst 95% OR user-provided indices).
    - Columns 0 to n_out-1 : True vs Pred for each output
    - Last column : Normalized error curve
    Now shows **unnormalized** geometry input X in each row title.
    """
    pred = results['pred']
    true = results['true']
    n_eval, n_freq, n_out = pred.shape

    Y_columns_cfg = config["dataset"].get("Y_columns", [])
    polar_defaults = ["gain_dB", "sin_phase", "cos_phase"]
    # Y_columns = list(Y_columns_cfg) + [
    #     polar_defaults[i] if i < len(polar_defaults) else f"out_{i}"
    #     for i in range(len(Y_columns_cfg), n_out)
    # ]

    if n_out == 3: #temporary, very bad
        Y_columns = polar_defaults
    else:
        Y_columns = Y_columns_cfg

    thresh_cfg = config.get("dataset", {}).get("threshold_low_weight", {})

    # ==================== UNNORMALIZE Y ====================
    pred_flat = pred.reshape(-1, n_out)
    true_flat = true.reshape(-1, n_out)
    pred = y_normalizer.inverse_transform(pred_flat).reshape(pred.shape)
    true = y_normalizer.inverse_transform(true_flat).reshape(true.shape)

    # ==================== SAMPLE SELECTION ====================
    if sample_indices is not None:
        selected_samples = np.asarray(sample_indices)
        n_samples = len(selected_samples)
    else:
        sample_error = np.mean((pred - true) ** 2, axis=(1, 2))
        p_low, p_high = percentile_range
        low = np.percentile(sample_error, p_low)
        high = np.percentile(sample_error, p_high)
        valid_mask = (sample_error >= low) & (sample_error <= high)
        selected_idx = np.linspace(0, np.sum(valid_mask) - 1, n_samples, dtype=int)
        selected_samples = np.where(valid_mask)[0][selected_idx]

    # Unnormalize X for titles (if provided)
    selected_X = None
    if X is not None:
        if x_normalizer is not None:
            X_shape = X.shape
            X_flat = X.reshape(-1, X_shape[-1]) if X.ndim > 1 else X.reshape(-1, 1)
            X_unnorm = x_normalizer.inverse_transform(X_flat).reshape(X_shape)
            selected_X = X_unnorm[selected_samples]
        else:
            selected_X = X[selected_samples]

    # ==================== Plotting ====================
    fig, axes = plt.subplots(
        n_samples, n_out + 1,
        figsize=(7.5 * (n_out + 1), 2.5 * n_samples),
        squeeze=False
    )

    for row, idx in enumerate(selected_samples):
        true_s = true[idx]
        pred_s = pred[idx]

        # Build geometry string for title
        x_info = ""
        if selected_X is not None:
            x_s = selected_X[row]
            if isinstance(x_s, np.ndarray) and x_s.ndim > 0:
                x_str = np.array2string(np.round(x_s, 4), separator=', ', suppress_small=True)
            else:
                x_str = f"{float(x_s):.4f}"
            x_info = f" | X={x_str}"

        # === True vs Prediction columns ===
        for c in range(n_out):
            ax = axes[row, c]
            ax.plot(true_s[:, c], label="True", linewidth=2.2, color='blue')
            ax.plot(pred_s[:, c], label="Pred", linestyle='--', linewidth=2.0, color='orange')
            ax.set_title(f"{Y_columns[c]}{x_info}")

            col_name = Y_columns[c]
            if col_name in thresh_cfg:
                tval = thresh_cfg[col_name].get("threshold")
                if tval is not None:
                    try:
                        ax.axhline(float(tval), color='red', linestyle='--', linewidth=1.8,
                                   alpha=0.85, label=f"thresh={tval}")
                    except Exception:
                        pass

            ax.legend(loc='upper right')
            ax.grid(True, alpha=0.35)
            if xlim is not None:
                ax.set_xlim(xlim)
                x_vals = np.arange(n_freq)
                mask = (x_vals >= xlim[0]) & (x_vals <= xlim[1])
                if np.any(mask):
                    y_data = np.concatenate([true_s[mask, c], pred_s[mask, c]])
                    if len(y_data) > 0:
                        y_min, y_max = y_data.min(), y_data.max()
                        padding = 0.05 * (y_max - y_min) if y_max > y_min else 1.0
                        ax.set_ylim(y_min - padding, y_max + padding)

        # === Normalized Error column ===
        ax = axes[row, n_out]
        ranges = np.ptp(true_s, axis=0) + 1e-8
        abs_err = np.abs(pred_s - true_s)
        norm_err = abs_err / ranges[None, :]
        mean_norm_err = np.mean(norm_err, axis=1)
        ax.plot(mean_norm_err, label="Mean Norm. Error", color='red', linewidth=2.2)
        ax.set_title(f"Normalized Error{x_info}")
        ax.set_ylim(0, 1.05)
        ax.legend(loc='upper right')
        ax.grid(True, alpha=0.35)
        if xlim is not None:
            ax.set_xlim(xlim)

    plt.tight_layout()
    save_dir = Path(save_dir)
    save_dir.mkdir(exist_ok=True)
    plt.savefig(save_dir / "predictions_vs_true.png", dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved: {save_dir}/predictions_vs_true.png")

def plot_amplitude_phase(
    results,
    config,
    save_dir,
    y_normalizer,
    n_samples=8,
    percentile_range=(5, 95),  # kept for backward compatibility (no longer used)
    xlim=None,
    X=None,
    axis=None,
    x_normalizer=None,
):
    """
    Amplitude (dB) + Phase (deg) plots for n_samples geometries.
    Samples are sorted by gain RMSE (lowest ? highest) from top to bottom.
    Returns the list of selected sample indices (so you can pass them to plot_predictions_vs_true).
    """
    pred = results['pred']
    true = results['true']
    n_out = pred.shape[-1]
    pred = y_normalizer.inverse_transform(pred.reshape(-1, n_out)).reshape(pred.shape)
    true = y_normalizer.inverse_transform(true.reshape(-1, n_out)).reshape(true.shape)

    complex_format = config.get("common", {}).get("complex_format", None)
    if complex_format == "polar" and n_out == 3:
        amp_true_db = true[..., 0]
        amp_pred_db = pred[..., 0]
        phase_true = np.degrees(np.arctan2(true[..., 1], true[..., 2]))
        phase_pred = np.degrees(np.arctan2(pred[..., 1], pred[..., 2]))
    else:
        amp_true_db = 20 * np.log10(np.sqrt(true[..., 0]**2 + true[..., 1]**2) + 1e-12)
        amp_pred_db = 20 * np.log10(np.sqrt(pred[..., 0]**2 + pred[..., 1]**2) + 1e-12)
        phase_true = np.degrees(np.arctan2(true[..., 1], true[..., 0]))
        phase_pred = np.degrees(np.arctan2(pred[..., 1], pred[..., 0]))

    # Per-point phase adjustment (unwrap to closest multiple of 180°)
    phase_pred_raw = phase_pred.copy()
    k = np.round((phase_true - phase_pred) / 180.0)
    phase_pred = phase_pred + 180.0 * k

    # Sort by gain RMSE (best ? worst)
    g_rmse_all = np.sqrt(np.mean((amp_pred_db - amp_true_db)**2, axis=1))
    sorted_idx = np.argsort(g_rmse_all)
    selected_samples = sorted_idx[
        np.linspace(
            int(len(sorted_idx) * (percentile_range[0] / 100)),
            int(len(sorted_idx) * (percentile_range[1] / 100)),
            n_samples,
            dtype=int,
        )
    ]

    # Unnormalize geometry for titles
    if X is not None and x_normalizer is not None:
        X_un = x_normalizer.inverse_transform(X.reshape(-1, X.shape[-1])).reshape(X.shape)
    else:
        X_un = X

    x_axis = axis if axis is not None else np.arange(amp_true_db.shape[1])
    xlabel = config["dataset"].get("axis_column", "Axis") if axis is not None else "Index"

    fig, axes = plt.subplots(
        n_samples, 2, figsize=(14, 3.2 * n_samples), squeeze=False
    )

    for row, idx in enumerate(selected_samples):
        g_rmse = float(np.sqrt(np.mean((amp_pred_db[idx] - amp_true_db[idx]) ** 2)))
        pd_diff = ((phase_pred[idx] - phase_true[idx] + 180) % 360) - 180
        p_rmse = float(np.sqrt(np.mean(pd_diff ** 2)))

        geom_str = ""
        if X_un is not None:
            xs = X_un[idx]
            geom_str = " | X = [" + ", ".join(f"{v:.3g}" for v in np.atleast_1d(xs)) + "]"

        # --- Amplitude ---
        ax0 = axes[row, 0]
        ax0.plot(x_axis, amp_true_db[idx], label="True", color="#1f77b4", linewidth=2.0)
        ax0.plot(
            x_axis,
            amp_pred_db[idx],
            label="Pred",
            color="#ff7f0e",
            linewidth=1.8,
            linestyle="--",
        )

        thresh_cfg = config.get("dataset", {}).get("threshold_low_weight", {})
        if "gain_dB" in thresh_cfg:
            tval = thresh_cfg["gain_dB"].get("threshold")
            if tval is not None:
                try:
                    ax0.axhline(
                        float(tval),
                        color="red",
                        linestyle="--",
                        linewidth=1.8,
                        alpha=0.85,
                        label=f"thresh={tval} dB",
                    )
                except Exception:
                    pass

        ax0.set_title(f"Sample #{idx} - Gain RMSE = {g_rmse:.2f} dB", fontsize=14)
        ax0.set_xlabel(xlabel, fontsize=14)
        ax0.set_ylabel("Gain (dB)", fontsize=14)
        ax0.legend(fontsize=14, loc="lower right")
        ax0.grid(True, alpha=0.35, linestyle="--")
        if xlim is not None:
            ax0.set_xlim(xlim)
        ax0.tick_params(axis="both", labelsize=13)

        # Ensure minimum y-range of 1 dB
        ymin, ymax = ax0.get_ylim()
        if ymax - ymin < 1.0:
            mid = 0.5 * (ymin + ymax)
            ax0.set_ylim(mid - 0.5, mid + 0.5)

        # --- Phase ---
        ax1 = axes[row, 1]
        ax1.plot(x_axis, phase_true[idx], label="True", color="#1f77b4", linewidth=2.0)
        ax1.plot(
            x_axis,
            phase_pred[idx],
            label="Pred",
            color="#ff7f0e",
            linewidth=1.8,
            linestyle="--",
        )
        ax1.set_title(f"Sample #{idx} - Phase RMSE = {p_rmse:.1f}°", fontsize=14)
        ax1.set_xlabel(xlabel, fontsize=14)
        ax1.set_ylabel("Phase (deg)", fontsize=14)
        ax1.set_ylim(-185, 185)
        ax1.set_yticks([-180, -90, 0, 90, 180])
        ax1.legend(fontsize=14, loc="lower right")
        ax1.grid(True, alpha=0.35, linestyle="--")
        if xlim is not None:
            ax1.set_xlim(xlim)
        ax1.tick_params(axis="both", labelsize=13)

    plt.tight_layout()
    save_dir = Path(save_dir)
    save_dir.mkdir(exist_ok=True)
    plt.savefig(save_dir / "amplitude_phase.png", dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Saved: {save_dir}/amplitude_phase.png")
    return selected_samples